
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teamspeak.fullname" . }}
  labels:
    {{- include "teamspeak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "teamspeak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "teamspeak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "teamspeak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: voice
          containerPort: 9987
          protocol: UDP
        - name: serverquery
          containerPort: 10011
          protocol: TCP
        - name: filetransfer
          containerPort: 30033
          protocol: TCP
        env:
        - name: TS3SERVER_LICENSE
          value: {{ .Values.teamspeak.license | quote }}
        {{- if .Values.teamspeak.serverName }}
        - name: TS3SERVER_SERVERQUERY_NAME
          value: {{ .Values.teamspeak.serverName | quote }}
        {{- end }}
        {{- if .Values.teamspeak.serverPassword }}
        - name: TS3SERVER_SERVER_PASSWORD
          value: {{ .Values.teamspeak.serverPassword | quote }}
        {{- end }}
        {{- if .Values.teamspeak.serverQueryPassword }}
        - name: TS3SERVER_SERVERQUERY_PASSWORD
          value: {{ .Values.teamspeak.serverQueryPassword | quote }}
        {{- end }}
        {{- if .Values.teamspeak.defaultVoicePort }}
        - name: TS3SERVER_DEFAULT_VOICE_PORT
          value: {{ .Values.teamspeak.defaultVoicePort | quote }}
        {{- end }}
        {{- if .Values.teamspeak.queryWhitelist }}
        - name: TS3SERVER_QUERY_IP_WHITELIST
          value: {{ .Values.teamspeak.queryWhitelist | quote }}
        {{- end }}
        {{- if .Values.teamspeak.queryBlacklist }}
        - name: TS3SERVER_QUERY_IP_BLACKLIST
          value: {{ .Values.teamspeak.queryBlacklist | quote }}
        {{- end }}
        {{- with .Values.teamspeak.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /var/ts3server
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "teamspeak.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
