apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamspeak.fullname" . }}
  labels:
    {{- include "teamspeak.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.service.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.hostname }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.service.voice.port }}
    targetPort: voice
    protocol: {{ .Values.service.voice.protocol }}
    name: voice
    {{- if and (eq .Values.service.type "NodePort") .Values.service.voice.nodePort }}
    nodePort: {{ .Values.service.voice.nodePort }}
    {{- end }}
  - port: {{ .Values.service.serverquery.port }}
    targetPort: serverquery
    protocol: {{ .Values.service.serverquery.protocol }}
    name: serverquery
    {{- if and (eq .Values.service.type "NodePort") .Values.service.serverquery.nodePort }}
    nodePort: {{ .Values.service.serverquery.nodePort }}
    {{- end }}
  - port: {{ .Values.service.filetransfer.port }}
    targetPort: filetransfer
    protocol: {{ .Values.service.filetransfer.protocol }}
    name: filetransfer
    {{- if and (eq .Values.service.type "NodePort") .Values.service.filetransfer.nodePort }}
    nodePort: {{ .Values.service.filetransfer.nodePort }}
    {{- end }}
  selector:
    {{- include "teamspeak.selectorLabels" . | nindent 4 }}
